[package]
name = 'xx_lib'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.26.0+a0f7474ae6bd74132efdb945d2eb2383f3913cce'
type = 'lib'
entry = 'xx_lib.nr'

[dependencies]
