[package]
name = 'tikan_pedersen'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.23.0+b3ddf10a2cbb80e88821baf7d76c478c3b98b3ea'
type = 'bin'
entry = 'pedersen.nr'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
