[package]
name = 'tikan_pedersen'
authors = [
  "Jordan Ellis Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.19.3+4e3a5a980b6739e9804e34d96f48d6bbcb31757f'
type = 'bin'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
