[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

#------------------------------------------------------------------------------

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "js"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'dprint', args = ["fmt", "--stdin", "md"] }

[[language]]
name = "typescript"
language-servers = [
  { name = "biome" },
  { name = "typescript-language-server", except-features = [ "format" ] }
]
formatter = { command = 'biome', args = ["format", "--stdin-file-path", "a.ts"] }
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "jsx"] }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "tsx"] }
auto-format = true

#------------------------------------------------------------------------------

[language-server.typescript-language-server]
config = { preferences = { importModuleSpecifierPreference = "non-relative" } }
