[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "js"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'dprint', args = ["fmt", "--stdin", "md"] }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "ts"] }
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "jsx"] }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'dprint', args = ["fmt", "--stdin", "tsx"] }
auto-format = true
