[package]
name = 'zz_player'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.25.0+3f676051a6073d6eabdc7fee68e4b522334344f6'
type = 'bin'
entry = 'zz_player.nr'

[dependencies]
lib = { path = '../zz_lib' }
