[package]
name = 'tikan_player'
authors = [
  "Jordan Ellis Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.20.0+54a1ed58c991eefa7ac9304b894c7046c294487b'
type = 'bin'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
