[package]
name = 'tikan_player'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.23.0+5e3c0f1dffb72961eb897ba90475eb9975e35cf3'
type = 'bin'
entry = 'player.nr'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
