[package]
name = 'tikan_player'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.23.0+5be9f9d7e2f39ca228df10e5a530474af0331704'
type = 'bin'
entry = 'player.nr'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
