[package]
name = 'tikan_player'
authors = [
  "Jordan Ellis Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.22.0+38c732c9dfc0c52cf4f020df6dea3bf628c376bb'
type = 'bin'

[dependencies]
lib = { path = '../lib' }
state = { path = '../lib/state' } # This is seemingly needed for `Board` to be seen.. what?
