White's turn: {
    shape: sequence_diagram
    white: White (Prover)
    black: Black (Verifier)

    output of prior turn: {
        black -> white: Black's state commitment
    }
    
    proving move to black: {
        white.a1 -> white.a1: Performs move creating\nnew board state
        white.a1 -> black: Proof new board state is valid
        white.a1 -> black: White's proposed state commitment
    }

    accepting white's move: {
        black.a1 -> black.a1: Verifies white's proof
        black.a1 -> black.a1: Applies white's move to it's own board state
    }
}