[package]
name = 'xx_aggregate'
authors = [
  "Jordan Ellis 'tsujp' Coppard <$(printf 'amMrZ2l0QHd6Lmh0Cg==' | base64 -d)>",
]
compiler_version = '0.36.0'
type = 'bin'
entry = 'xx_aggregate.nr'

[dependencies]
lib = { path = '../xx_lib' }
